### ISSUE TITLE
trouble compiling

### ISSUE THREAD

**Issue by maksw2** [nooodles-ahh/video_services#3]
Error	3	error C2666: 'pow' : 6 overloads have similar conversions	c:\users\maksw\documents\source-sdk-2013\mp\src\video_services\video_services\video_material.cpp	873
i am using vs 2013 premium.

**Comment by nooodles-ahh** [comment]
Try replacing `pow` at line 873 with `powf` or `FastPow`

**Comment by maksw2** [comment]
Warning	1	warning C4800: 'vpx_codec_ctx *const ' : forcing value to bool 'true' or 'false' (performance warning) (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\vpxdecoder.hpp	65	1	Video Services
Warning	2	warning C4244: '=' : conversion from 'int' to 'short', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\opusvorbisdecoder.cpp	104	1	Video Services
Warning	3	warning C4244: 'argument' : conversion from 'double' to 'opus_int32', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\opusvorbisdecoder.cpp	206	1	Video Services
Warning	4	warning C4244: '=' : conversion from 'double' to 'int', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\opusvorbisdecoder.cpp	209	1	Video Services
Warning	5	warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\webmdemuxer.cpp	119	1	Video Services
Warning	6	warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\webmdemuxer.cpp	123	1	Video Services
Warning	7	warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\webmdemuxer.cpp	140	1	Video Services
Warning	8	warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\webmdemuxer.cpp	144	1	Video Services
Warning	9	warning C4244: 'initializing' : conversion from '__int64' to 'const long', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\webmdemuxer.cpp	209	1	Video Services
Warning	10	warning C4244: 'initializing' : conversion from '__int64' to 'const long', possible loss of data	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\webmdemuxer.cpp	243	1	Video Services
Warning	11	warning C4505: 'vpx_codec_control_VP8_SET_REFERENCE' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8.h	120	1	Video Services
Warning	12	warning C4505: 'vpx_codec_control_VP8_COPY_REFERENCE' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8.h	122	1	Video Services
Warning	13	warning C4505: 'vpx_codec_control_VP8_SET_POSTPROC' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8.h	124	1	Video Services
Warning	14	warning C4505: 'vpx_codec_control_VP9_GET_REFERENCE' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8.h	126	1	Video Services
Warning	15	warning C4505: 'vpx_codec_control_VP8D_GET_LAST_REF_UPDATES' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	190	1	Video Services
Warning	16	warning C4505: 'vpx_codec_control_VP8D_GET_FRAME_CORRUPTED' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	192	1	Video Services
Warning	17	warning C4505: 'vpx_codec_control_VP8D_GET_LAST_REF_USED' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	194	1	Video Services
Warning	18	warning C4505: 'vpx_codec_control_VPXD_SET_DECRYPTOR' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	196	1	Video Services
Warning	19	warning C4505: 'vpx_codec_control_VP8D_SET_DECRYPTOR' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	198	1	Video Services
Warning	20	warning C4505: 'vpx_codec_control_VP9D_GET_FRAME_SIZE' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	200	1	Video Services
Warning	21	warning C4505: 'vpx_codec_control_VP9D_GET_DISPLAY_SIZE' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	202	1	Video Services
Warning	22	warning C4505: 'vpx_codec_control_VP9D_GET_BIT_DEPTH' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	204	1	Video Services
Warning	23	warning C4505: 'vpx_codec_control_VP9_SET_BYTE_ALIGNMENT' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	206	1	Video Services
Warning	24	warning C4505: 'vpx_codec_control_VP9_INVERT_TILE_DECODE_ORDER' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	208	1	Video Services
Warning	25	warning C4505: 'vpx_codec_control_VP9_SET_SKIP_LOOP_FILTER' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	210	1	Video Services
Warning	26	warning C4505: 'vpx_codec_control_VP9_DECODE_SVC_SPATIAL_LAYER' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	212	1	Video Services
Warning	27	warning C4505: 'vpx_codec_control_VPXD_GET_LAST_QUANTIZER' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	214	1	Video Services
Warning	28	warning C4505: 'vpx_codec_control_VP9D_SET_ROW_MT' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	216	1	Video Services
Warning	29	warning C4505: 'vpx_codec_control_VP9D_SET_LOOP_FILTER_OPT' : unreferenced local function has been removed (VPXDecoder.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\includes\vpx\vp8dx.h	218	1	Video Services
Warning	30	warning C4800: 'vpx_codec_ctx *const ' : forcing value to bool 'true' or 'false' (performance warning) (video_material.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\vpxdecoder.hpp	65	1	Video Services
Warning	31	warning C4800: 'vpx_codec_ctx *const ' : forcing value to bool 'true' or 'false' (performance warning) (video_services.cpp)	c:\users\user\desktop\source-sdk-2013\mp\src\video_services\video_services\vpxdecoder.hpp	65	1	Video Services
Error	32	error LNK2038: mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in libwebm.lib(mkvparser.obj)	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\libcpmt.lib(nothrow.obj)	Video Services
Error	33	error LNK2019: unresolved external symbol "void __stdcall `eh vector constructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *),void (__thiscall*)(void *))" (??_L@YGXPAXIIP6EX0@Z1@Z) referenced in function "private: bool __thiscall mkvparser::Chapters::Edition::ExpandAtomsArray(void)" (?ExpandAtomsArray@Edition@Chapters@mkvparser@@AAE_NXZ)	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\libwebm.lib(mkvparser.obj)	Video Services
Error	34	error LNK2019: unresolved external symbol "void __stdcall `eh vector destructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *))" (??_M@YGXPAXIIP6EX0@Z@Z) referenced in function "public: __thiscall mkvparser::Chapters::~Chapters(void)" (??1Chapters@mkvparser@@QAE@XZ)	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\libwebm.lib(mkvparser.obj)	Video Services
Error	35	error LNK2019: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z) referenced in function "public: __thiscall std::unique_ptr<struct mkvparser::MasteringMetadata,struct std::default_delete<struct mkvparser::MasteringMetadata> >::~unique_ptr<struct mkvparser::MasteringMetadata,struct std::default_delete<struct mkvparser::MasteringMetadata> >(void)" (??1?$unique_ptr@UMasteringMetadata@mkvparser@@U?$default_delete@UMasteringMetadata@mkvparser@@@std@@@std@@QAE@XZ)	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\libwebm.lib(mkvparser.obj)	Video Services
Error	36	error LNK2019: unresolved external symbol "void __cdecl operator delete[](void *,unsigned int)" (??_V@YAXPAXI@Z) referenced in function "public: __thiscall mkvparser::Chapters::~Chapters(void)" (??1Chapters@mkvparser@@QAE@XZ)	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\libwebm.lib(mkvparser.obj)	Video Services
Error	37	error LNK2001: unresolved external symbol ___std_terminate	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\libwebm.lib(mkvparser.obj)	Video Services
Error	38	error LNK2019: unresolved external symbol ___acrt_iob_func referenced in function _celt_fatal	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\opus.lib(celt.obj)	Video Services
Error	39	error LNK2019: unresolved external symbol ___stdio_common_vfprintf referenced in function _fprintf	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\opus.lib(celt.obj)	Video Services
Error	40	error LNK1120: 7 unresolved externals	C:\Users\User\Desktop\source-sdk-2013\mp\src\video_services\video_services\Release\\video_services.dll	Video Services

**Comment by nooodles-ahh** [comment]
You might want to use an SDK more modern like [Nbc66/source-sdk-2013-ce](https://github.com/Nbc66/source-sdk-2013-ce), as I haven't actually tested it on the original distribution of the SDK, nor do I know if all the dependencies would actually compile on VS2013. If you just need the compiled files they are in releases.

**Comment by maksw2** [comment]
okay thanks.
